'$schema' = 'https://starship.rs/config-schema.json'

format = """
[](peach)\
$os\
$username\
$hostname\
[ ](bg:yellow fg:peach)\
$directory\
[ ](fg:yellow)\
"""

right_format = """
$character\
[](bg:base fg:subtext1)\
$git_branch\
$git_status\
[](bg:subtext1 fg:overlay1)\
$cmd_duration\
$time\
[](fg:overlay1)\
"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = '#f5e0dc'
flamingo = '#f2cdcd'
pink = '#f5c2e7'
mauve = '#cba6f7'
red = '#f38ba8'
maroon = '#eba0ac'
peach = '#fab387'
yellow = '#f9e2af'
green = '#a6e3a1'
teal = '#94e2d5'
sky = '#89dceb'
sapphire = '#74c7ec'
blue = '#89b4fa'
lavender = '#b4befe'
text = '#cdd6f4'
subtext1 = '#bac2de'
subtext0 = '#a6adc8'
overlay2 = '#9399b2'
overlay1 = '#7f849c'
overlay0 = '#6c7086'
surface2 = '#585b70'
surface1 = '#45475a'
surface0 = '#313244'
base = '#1e1e2e'
mantle = '#181825'
crust = '#11111b'

[os]
disabled = false
style = 'bg:peach fg:base'
format = "[$symbol ]($style)"

[os.symbols]
Macos = ''

[username]
show_always = true
format = '[$user ]($style)'
style_user = "bg:peach fg:base"
style_root = "bg:peach fg:base"

[hostname]
disabled = false
ssh_only = true
format = "[@$hostname ]($style)"
style = "bg:peach fg:base"

[directory]
format = "[$path ]($style)"
style = "bg:yellow fg:base"
truncation_length = 3
# truncation_symbol = ".../"
fish_style_pwd_dir_length = 2

[character]
success_symbol = '🚀'
error_symbol = '🔥'

[git_branch]
format = '[[ $symbol $branch ](bg:subtext1 fg:base)]($style)'
symbol = ""
# symbol = ""

[git_status]
disabled = true
format = '[[($all_status$ahead_behind )](bg:subtext1 fg:base)]($style)'
style = "bg:color_aqua"

[cmd_duration]
min_time = 500
format = '[ took $duration](bg:overlay1 fg:base)'

[time]
disabled = false
time_format = "%R"
style = "bg:overlay1"
format = '[[ at $time ](bg:overlay1 fg:base)]($style)'
# format = '[[  $time ](bg:overlay1 fg:base)]($style)'
